### PR TITLE
Fix append to fields.

### LINKED ISSUE #17: With overwrites Fields instead of appending
https://github.com/teltech/logger/blob/061abb56355428c7f85f016472eb462cff25b368/logger.go#L166

### PR DESCRIPTION
**Pull request by ShawnMilo**
Before, creating a new logger with `With` would overwrite the fields of the "parent" logger. Now it appends to them.

Fixes #17.

### CODE REVIEW

File: logger.go [hunk 1]
```diff
@@ -157,8 +157,34 @@ func isValidLogLevel(s severity) bool {
...
+	}
+	return f
+
+}
+
 // With is used as a chained method to specify which values go in the log entry's context
 func (l *Log) With(fields Fields) *Log {
+
+	for k, v := range l.fields() {
+		fields[k] = v
```
Comment (mpeguerus) [inline logger.go]: I think you should not override `fields` with the `parent fields`, should be the opposite,  `parent fields` should be overridden by the `fields`.

File: logger.go [hunk 2]
```diff
@@ -157,8 +157,34 @@ func isValidLogLevel(s severity) bool {
...
+
+	if l.payload.Context.Data == nil {
+		return f
+	}
+
+	for k, v := range l.payload.Context.Data {
+		f[k] = v
+	}
+	return f
+
```
[the remark this answers is not in the document]
Comment (ShawnMilo) [reply logger.go]: Fixed.

File: logger.go (hunk 1 above)
Comment (ShawnMilo) [reply logger.go]: Excellent catch! Fixed.
